// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDEnaimVJJNkUoZPxQ2zDcZloZuwtwq2yg',
    appId: '1:758925525394:web:72f317aac473d346c3414b',
    messagingSenderId: '758925525394',
    projectId: 'cujammu-b9893',
    authDomain: 'cujammu-b9893.firebaseapp.com',
    storageBucket: 'cujammu-b9893.firebasestorage.app',
    measurementId: 'G-GY73FNC34P',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDZ91ChEviZC2DqOGrWbUOTFVHd1AMLP3k',
    appId: '1:758925525394:android:fcc12c9f6f91c87ac3414b',
    messagingSenderId: '758925525394',
    projectId: 'cujammu-b9893',
    storageBucket: 'cujammu-b9893.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCqfJ_ShmiaHYPgFhFYun77f_J1qkcBzjo',
    appId: '1:758925525394:ios:370aa8988a70d981c3414b',
    messagingSenderId: '758925525394',
    projectId: 'cujammu-b9893',
    storageBucket: 'cujammu-b9893.firebasestorage.app',
    androidClientId: '758925525394-h167gkp6g2m0r3jtmt6k35evi780seb1.apps.googleusercontent.com',
    iosClientId: '758925525394-bol3i6fbjpla72otm2qiqphonafm89hl.apps.googleusercontent.com',
    iosBundleId: 'com.example.cuj',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCqfJ_ShmiaHYPgFhFYun77f_J1qkcBzjo',
    appId: '1:758925525394:ios:370aa8988a70d981c3414b',
    messagingSenderId: '758925525394',
    projectId: 'cujammu-b9893',
    storageBucket: 'cujammu-b9893.firebasestorage.app',
    androidClientId: '758925525394-h167gkp6g2m0r3jtmt6k35evi780seb1.apps.googleusercontent.com',
    iosClientId: '758925525394-bol3i6fbjpla72otm2qiqphonafm89hl.apps.googleusercontent.com',
    iosBundleId: 'com.example.cuj',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDEnaimVJJNkUoZPxQ2zDcZloZuwtwq2yg',
    appId: '1:758925525394:web:6bda71d0bc7d7a69c3414b',
    messagingSenderId: '758925525394',
    projectId: 'cujammu-b9893',
    authDomain: 'cujammu-b9893.firebaseapp.com',
    storageBucket: 'cujammu-b9893.firebasestorage.app',
    measurementId: 'G-M3DGC5LWXR',
  );

}